task: MNIST
synthesizer: Pattern

batch_size: 64
test_batch_size: 100
lr: 0.01
momentum: 0.9
decay: 0.0005
epochs: 1
save_on_epochs: []
optimizer: SGD
log_interval: 100
scheduler: False

poisoning_proportion: 1.0
backdoor_label: 8
backdoor_label2: 8
backdoor: True
backdoor_dynamic_position: False

loss_balance: MGDA
mgda_normalize: loss

save_model: Ture
log: Ture
tb: Ture

#resume_model: MNIST_badnets.pth
# resume_model: MNIST_SIN1.pth

transform_train: True

#resume_model: lenet_mnist_model.pth

loss_tasks:
#  - backdoor3
#  - backdoor4
#  - backdoor2
  - backdoor
  - normal
#  - neural_cleanse
#  - sentinet_evasion



#poison_images_test:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588
#
#poison_images:
#  - 389
#  - 561
#  - 874
#  - 1605
#  - 3378
#  - 3678
#  - 4528
#  - 9744
#  - 19165
#  - 19500
#  - 21422
#  - 22984
#  - 32941
#  - 34287
#  - 34385
#  - 36005
#  - 37365
#  - 37533
#  - 38658
#  - 38735
#  - 39824
#  - 40138
#  - 41336
#  - 41861
#  - 47001
#  - 47026
#  - 48003
#  - 48030
#  - 49163
#  - 49588